{
  "build_from":
    {
      "amd64": "itzg/minecraft-server:latest:java8-multiarch",
      "aarch64": "itzg/minecraft-server:latest:java8-multiarch",
      "armv7": "itzg/minecraft-server:latest:java8-multiarch",
    },
}
